Changes for new version control system
godotengine/godot-git-plugin pull request #47
Opened 2020-09-05 10:26 UTC by Janglee123

It is based on libgit2-bump-fix and requires [vcs-new-ui](https://github.com/Janglee123/godot/tree/vcs-new-ui) to work. Both branches are updated parallelly.

2020-09-06 01:30 UTC, IronicallySerious commented
@Janglee123 Could you rebase this on the current master? Also, there are some merge conflicts now, which I guess are quite small. Just use the build_libs.bat changes exactly as in the master branch, except if you are adding some new CMake flags

2020-09-06 01:31 UTC, IronicallySerious requested changes

2020-09-06 01:31 UTC, IronicallySerious commented on SConstruct
> +env.Append(LIBS=[cpp_library, 'ssl', 'crypto', 'ssh2', 'git2'])
Also this should be added in the x11 section above, as I said on Matrix

2021-04-19 18:51 UTC, ChronicallySerious commented
Simply updating this branch to master by a basic merge for now because all that has changed in master, which is minimal C++ code changes but still a lot of build scripts and CI configs.

2021-06-13 05:46 UTC, Janglee123 commented
Updated for Godot 3.x branch.

2021-09-28 07:10 UTC, ChronicallySerious commented
Updating this branch to run macOS arm arch CI

2022-01-10 15:00 UTC, merged